services:
    nuxt:
        container_name: nuxt
        build:
            context: .
            dockerfile: ./frontend/Dockerfile.development
        volumes:
            - ./frontend:/app:cached
            - nuxt_node_modules:/app/node_modules
        ports:
            - '3000:3000'
            - '24678:24678'
        tty: true
        environment:
            - HOST=0.0.0.0
            - port=3000
            - CHOKIDAR_USEPOLLING=true
        command: npm run dev -- -o

    fastapi:
        container_name: fastapi
        build:
            context: .
            dockerfile: ./backend/Dockerfile.development
        volumes:
            - ./backend:/code
        ports:
            - '8000:8000'
        tty: true
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword
        ports:
            - '3306:3306'
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    nuxt_node_modules:
    mysql_data:
