services:
    nuxt:
        container_name: nuxt
        build:
            context: .
            dockerfile: ./docker/nuxt/Dockerfile
        volumes:
            - ./frontend:/app:cached
            - nuxt_node_modules:/app/node_modules
        ports:
            - '3000:3000'
            - '24678:24678'
        tty: true
        environment:
            - HOST=0.0.0.0
            - port=3000
            - CHOKIDAR_USEPOLLING=true
        command: sh -c "npm run dev -- -o"
    fastapi:
        container_name: fastapi
        build:
            context: .
            dockerfile: ./docker/fastapi/Dockerfile
        volumes:
            - ./backend:/code
        ports:
            - '8000:8000'
        tty: true
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
volumes:
    nuxt_node_modules:
