services:
    nuxt:
        container_name: nuxt
        build:
            context: .
            dockerfile: ./frontend/Dockerfile.development
        volumes:
            - ./frontend:/app:cached
            - nuxt_node_modules:/app/node_modules
        ports:
            - '3000:3000'
            - '24678:24678'
        tty: true
        environment:
            - HOST=0.0.0.0
            - port=3000
            - CHOKIDAR_USEPOLLING=true
        command: npm run dev -- -o

    fastapi:
        container_name: fastapi
        build:
            context: .
            dockerfile: ./backend/Dockerfile.development
        volumes:
            - ./backend:/code
        ports:
            - '8000:8000'
        tty: true
        command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

    db:
        image: postgres:16
        container_name: postgres-db
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
volumes:
    nuxt_node_modules:
    postgres_data:
