FROM python:3.12.0

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./serviceAccountKey.json /code/serviceAccountKey.json

ENV ENV=production

COPY ./.env.production /code/.env.production

COPY ./app /code/app

COPY ./migration /code/migration

COPY ./alembic.ini /code/alembic.ini

EXPOSE 8080

COPY ./entrypoint.sh /code/entrypoint.sh

RUN chmod +x /code/entrypoint.sh

CMD ["/code/entrypoint.sh"]