"""edit team table3

Revision ID: 0432bd9d77dc
Revises: f232082548d8
Create Date: 2024-11-02 06:04:13.643665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0432bd9d77dc'
down_revision: Union[str, None] = 'f232082548d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'X_user_name')
    op.drop_column('matches', 'instagram_user_name')
    op.add_column('teams', sa.Column('instagram_user_name', sa.String(length=30), nullable=True))
    op.add_column('teams', sa.Column('X_user_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'X_user_name')
    op.drop_column('teams', 'instagram_user_name')
    op.add_column('matches', sa.Column('instagram_user_name', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('matches', sa.Column('X_user_name', mysql.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
