"""update team table

Revision ID: 167d3e824ebe
Revises: 4076f5d8fb61
Create Date: 2024-11-02 10:41:09.897716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '167d3e824ebe'
down_revision: Union[str, None] = '4076f5d8fb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'instagram_user_name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('teams', 'X_user_name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'X_user_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('teams', 'instagram_user_name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
