"""edit team table

Revision ID: 6b4e291f2ec5
Revises: 
Create Date: 2024-11-02 06:00:48.092797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b4e291f2ec5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('instagram_user_name', sa.String(length=20), nullable=True))
    op.add_column('matches', sa.Column('X_user_name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'X_user_name')
    op.drop_column('matches', 'instagram_user_name')
    # ### end Alembic commands ###
