"""edit team table2

Revision ID: f232082548d8
Revises: 6b4e291f2ec5
Create Date: 2024-11-02 06:03:16.279796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f232082548d8'
down_revision: Union[str, None] = '6b4e291f2ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'instagram_user_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.alter_column('matches', 'X_user_name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'X_user_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('matches', 'instagram_user_name',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
